ALTER TYPE asset_action ADD VALUE IF NOT EXISTS 'ISSUE_REPORTED';
ALTER TYPE asset_action ADD VALUE IF NOT EXISTS 'ACKNOWLEDGED';
ALTER TYPE asset_action ADD VALUE IF NOT EXISTS 'ASSIGNMENT_REQUESTED';
ALTER TYPE asset_action ADD VALUE IF NOT EXISTS 'ASSIGNMENT_APPROVED';
ALTER TYPE asset_action ADD VALUE IF NOT EXISTS 'ASSIGNMENT_REJECTED';
