ALTER TABLE branches ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE branches ADD COLUMN archived_at TIMESTAMPTZ;
ALTER TABLE departments ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE departments ADD COLUMN archived_at TIMESTAMPTZ;
